version: "3.9"

services:
  bubblymaps:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      # AUTH
      - DATABASE_URL=postgresql://your_db_username:your_db_password@10.0.0.141:5432/bubblymaps
      - AUTH_SECRET=your_auth_secret_here
      - AUTH_GOOGLE_ID=your_google_client_id
      - AUTH_GOOGLE_SECRET=your_google_client_secret
      - AUTH_TRUST_HOST=https://yourdomain.com
      - AUTH_RESEND_KEY=your_resend_api_key
      - NEXTAUTH_URL=https://yourdomain.com # legacy for resend
      # MINIO
      - MINIO_URL=https://your-s3-endpoint.com
      - MINIO_BUCKET=your-bucket-name
      - MINIO_USER=your_minio_username
      - MINIO_PASS=your_minio_password
      # BUBBLY MAPS API
      - APP_URL=https://yourdomain.com
      - API_TOKEN=your_api_token
      # LOGGING
      - DISCORD_WEBHOOK_URL=your_discord_webhook_url
      # DEBUG
      - APP_VERSION=v5.0.3
      - API_VERSION=v6
    depends_on:
      - postgres
      - minio
    networks:
      - bubblymaps

  postgres:
    image: postgres:15
    container_name: bubblymaps-postgres
    restart: always

    ports:
      - "5432:5432" # Db

    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      PGDATA: /var/lib/postgresql/data

    volumes:
      - /opt/services/postgres:/var/lib/postgresql/data

    networks:
      - bubblymaps

  minio:
    image: minio/minio:latest
    container_name: bubblymaps-minio
    restart: always

    ports:
      - "9002:9000"  # API
      - "9001:9001"  # Console

    environment:
      MINIO_ROOT_USER: your_minio_username
      MINIO_ROOT_PASSWORD: your_minio_password

    volumes:
      - /opt/services/minio:/data

    command: server /data --console-address ":9001"

    networks:
      - bubblymaps

networks:
  bubblymaps:
    name: bubblymaps-net
